USE AdventureWorks;

SELECT * FROM sys.databases;
SELECT * FROM sys.schemas;
SELECT * FROM sys.tables;
SELECT * FROM sys.columns;
SELECT * FROM sys.objects;
SELECT * FROM sys.views;
SELECT * FROM sys.procedures;
SELECT * FROM sys.triggers;

SELECT SCHEMA_NAME(4);
SELECT OBJECT_NAME(3);
SELECT SCHEMA_ID('sys');
SELECT OBJECT_ID('sys.sysrscols');


--SQL 2005
SELECT * FROM INFORMATION_SCHEMA.SCHEMATA;
SELECT * FROM INFORMATION_SCHEMA.TABLES;
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
SELECT * FROM INFORMATION_SCHEMA.VIEWS;
SELECT * FROM INFORMATION_SCHEMA.ROUTINES;
SELECT * FROM INFORMATION_SCHEMA.SEQUENCES;

SELECT * FROM INFORMATION_SCHEMA.ROUTINE_COLUMNS
